#pragma once 
#include <glad/glad.h>
#include <SDL.h>
#include <SDL_image.h>
#include <glm/glm.hpp>
#include <spdlog/spdlog.h>
#include "Window.h"
#include "Sprite.h"
#include "Shader.h"
#include "Painter.h"
